services:
  # ============= BASES DE DATOS =============
  mongodb:
    image: mongo:6.0
    container_name: hotel_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: hotels_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - hotel_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mysql:
    image: mysql:8.0
    container_name: hotel_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: booking_db
      MYSQL_USER: booking_user
      MYSQL_PASSWORD: booking_pass
      # ✅ AGREGADO: Permitir conexiones remotas
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./booking-service/sql:/docker-entrypoint-initdb.d
    networks:
      - hotel_network
    # ✅ AGREGADO: Comando para configurar MySQL correctamente
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # ============= MESSAGING Y SEARCH =============
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: hotel_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - hotel_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 8
      start_period: 30s

  solr:
    image: solr:9.2
    container_name: hotel_solr
    ports:
      - "8983:8983"
    environment:
      SOLR_HEAP: 1g
    volumes:
      - solr_data:/var/solr
    command: solr-precreate hotels
    networks:
      - hotel_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/hotels/admin/ping"]
      interval: 10s
      timeout: 5s
      retries: 8
      start_period: 30s

  # ============= CACHE =============
  memcached:
    image: memcached:1.6-alpine
    container_name: hotel_memcached
    ports:
      - "11211:11211"
    networks:
      - hotel_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  # ============= MICROSERVICIOS =============
  hotel-service:
    build: ./hotel-service
    container_name: hotel_service
    ports:
      - "8001:8080"  # Puerto externo 8001, interno 8080
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/hotels_db?authSource=admin
      - RABBITMQ_URI=amqp://admin:admin123@rabbitmq:5672/
      - PORT=8080
    volumes:
      # Volumen para persistir imágenes subidas
      - hotel_uploads:/app/uploads
    networks:
      - hotel_network
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  search-service:
    build: ./search-service
    container_name: search_service
    ports:
      - "8002:8080"
    environment:
      - SOLR_URI=http://solr:8983/solr/hotels
      - RABBITMQ_URI=amqp://admin:admin123@rabbitmq:5672/
      - HOTEL_SERVICE_URI=http://hotel-service:8080
      - PORT=8080
    networks:
      - hotel_network
    depends_on:
      solr:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      hotel-service:
        condition: service_started
    restart: unless-stopped
    # HEALTHCHECK REMOVIDO TEMPORALMENTE

  booking-service:
    build: ./booking-service
    container_name: booking_service
    ports:
      - "8003:8080"
    environment:
      - MYSQL_URI=booking_user:booking_pass@tcp(mysql:3306)/booking_db
      - MEMCACHED_URI=memcached:11211
      - HOTEL_SERVICE_URI=http://hotel-service:8080
      - PORT=8080
      - JWT_SECRET=mi-secreto-super-seguro-2024
    networks:
      - hotel_network
    depends_on:
      mysql:
        condition: service_healthy
      memcached:
        condition: service_healthy
      hotel-service:
        condition: service_started
    restart: unless-stopped
    # HEALTHCHECK REMOVIDO TEMPORALMENTE

  # ============= FRONTEND =============
  frontend:
    build: ./frontend
    container_name: hotel_frontend
    ports:
      - "3000:80"  # Nginx runs on port 80 inside container
    environment:
      - REACT_APP_HOTEL_SERVICE=http://localhost:8001
      - REACT_APP_SEARCH_SERVICE=http://localhost:8002
      - REACT_APP_BOOKING_SERVICE=http://localhost:8003
    networks:
      - hotel_network
    depends_on:
      - hotel-service
      - search-service
      - booking-service

volumes:
  mongodb_data:
  mysql_data:
  rabbitmq_data:
  solr_data:
  hotel_uploads:  # Volumen para imágenes de hoteles

networks:
  hotel_network:
    driver: bridge